package com.example.composechatsample.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

@Immutable
public data class StreamDimens(
    public val channelItemVerticalPadding: Dp,
    public val channelItemHorizontalPadding: Dp,
    public val channelAvatarSize: Dp,
    public val selectedChannelMenuUserItemWidth: Dp,
    public val selectedChannelMenuUserItemHorizontalPadding: Dp,
    public val selectedChannelMenuUserItemAvatarSize: Dp,
    public val attachmentsContentImageWidth: Dp,
    public val attachmentsContentGiphyWidth: Dp,
    public val attachmentsContentGiphyHeight: Dp,
    public val attachmentsContentLinkWidth: Dp,
    public val attachmentsContentFileWidth: Dp,
    public val attachmentsContentFileUploadWidth: Dp,
    public val attachmentsContentUnsupportedWidth: Dp,
    public val threadSeparatorVerticalPadding: Dp,
    public val threadSeparatorTextVerticalPadding: Dp,
    public val messageOptionsItemHeight: Dp,
    public val suggestionListMaxHeight: Dp,
    public val suggestionListPadding: Dp,
    public val suggestionListElevation: Dp,
    public val mentionSuggestionItemHorizontalPadding: Dp,
    public val mentionSuggestionItemVerticalPadding: Dp,
    public val mentionSuggestionItemAvatarSize: Dp,
    public val commandSuggestionItemHorizontalPadding: Dp,
    public val commandSuggestionItemVerticalPadding: Dp,
    public val commandSuggestionItemIconSize: Dp,
    public val threadParticipantItemSize: Dp,
    public val userReactionsMaxHeight: Dp,
    public val userReactionItemWidth: Dp,
    public val userReactionItemAvatarSize: Dp,
    public val userReactionItemIconSize: Dp,
    public val reactionOptionItemIconSize: Dp,
    public val headerElevation: Dp,
    public val messageItemMaxWidth: Dp,
    public val quotedMessageTextVerticalPadding: Dp,
    public val quotedMessageTextHorizontalPadding: Dp,
    public val quotedMessageAttachmentPreviewSize: Dp,
    public val quotedMessageAttachmentTopPadding: Dp,
    public val quotedMessageAttachmentBottomPadding: Dp,
    public val quotedMessageAttachmentStartPadding: Dp,
    public val quotedMessageAttachmentEndPadding: Dp,
    public val groupAvatarInitialsXOffset: Dp,
    public val groupAvatarInitialsYOffset: Dp,
    public val attachmentsContentImageMaxHeight: Dp,
    public val attachmentsContentGiphyMaxWidth: Dp = attachmentsContentGiphyWidth,
    public val attachmentsContentGiphyMaxHeight: Dp = attachmentsContentGiphyHeight,
    public val attachmentsContentVideoMaxHeight: Dp,
    public val attachmentsContentMediaGridSpacing: Dp,
    public val attachmentsContentVideoWidth: Dp,
    public val attachmentsContentGroupPreviewWidth: Dp,
    public val attachmentsContentGroupPreviewHeight: Dp,
) {

    public companion object {

        public fun defaultDimens(): StreamDimens = StreamDimens(
            channelItemVerticalPadding = 12.dp,
            channelItemHorizontalPadding = 8.dp,
            channelAvatarSize = 40.dp,
            selectedChannelMenuUserItemWidth = 80.dp,
            selectedChannelMenuUserItemHorizontalPadding = 8.dp,
            selectedChannelMenuUserItemAvatarSize = 64.dp,
            attachmentsContentImageWidth = 250.dp,
            attachmentsContentGiphyWidth = 250.dp,
            attachmentsContentGiphyHeight = 200.dp,
            attachmentsContentLinkWidth = 250.dp,
            attachmentsContentFileWidth = 250.dp,
            attachmentsContentFileUploadWidth = 250.dp,
            attachmentsContentUnsupportedWidth = 250.dp,
            threadSeparatorVerticalPadding = 8.dp,
            threadSeparatorTextVerticalPadding = 2.dp,
            messageOptionsItemHeight = 40.dp,
            suggestionListMaxHeight = 256.dp,
            suggestionListPadding = 8.dp,
            suggestionListElevation = 4.dp,
            mentionSuggestionItemHorizontalPadding = 16.dp,
            mentionSuggestionItemVerticalPadding = 8.dp,
            mentionSuggestionItemAvatarSize = 40.dp,
            commandSuggestionItemHorizontalPadding = 8.dp,
            commandSuggestionItemVerticalPadding = 8.dp,
            commandSuggestionItemIconSize = 24.dp,
            threadParticipantItemSize = 16.dp,
            userReactionsMaxHeight = 256.dp,
            userReactionItemWidth = 80.dp,
            userReactionItemIconSize = 24.dp,
            userReactionItemAvatarSize = 64.dp,
            reactionOptionItemIconSize = 24.dp,
            headerElevation = 4.dp,
            messageItemMaxWidth = 250.dp,
            quotedMessageTextHorizontalPadding = 8.dp,
            quotedMessageTextVerticalPadding = 6.dp,
            quotedMessageAttachmentPreviewSize = 36.dp,
            quotedMessageAttachmentBottomPadding = 6.dp,
            quotedMessageAttachmentTopPadding = 6.dp,
            quotedMessageAttachmentStartPadding = 8.dp,
            quotedMessageAttachmentEndPadding = 0.dp,
            groupAvatarInitialsXOffset = 1.5.dp,
            groupAvatarInitialsYOffset = 2.5.dp,
            attachmentsContentImageMaxHeight = 600.dp,
            attachmentsContentVideoMaxHeight = 400.dp,
            attachmentsContentMediaGridSpacing = 2.dp,
            attachmentsContentVideoWidth = 250.dp,
            attachmentsContentGroupPreviewWidth = 250.dp,
            attachmentsContentGroupPreviewHeight = 250.dp,
        )
    }
}